name: 'Submit Pull Request'
description: 'Submit a pull request associated with the issue'
inputs:
  GITHUB_ACCESS_TOKEN:
    description: 'GITHUB_TOKEN or a `repo` scoped Personal Access Token'
    required: true
  LABEL:
    description: 'Comma separated label names to label the submitted pull request ex.) "bugfix,feature,new_commer"'
    required: false
  ASSIGN:
    description: 'Choose to assign the committed user'
    default: true
    required: false
  LABEL_SAME_AS_ISSUE:
    description: 'Choose to label to pr same as issue'
    default: true
    required: false
runs:
  using: "docker"
  image: "Dockerfile"
branding:
  icon: 'git-pull-request'
  color: 'orange'
